#!/usr/bin/env bash

VLC=$(command -v cvlc)
CONVERT=$(command -v convert)

if [ -z "${VLC_SOURCE_1X1}" ]; then
    echo "Source 1,1 not defined (VLC_SOURCE_1X1)"
    exit 1
fi

if [ -z "${VLC_SOURCE_2X1}" ]; then
    echo "Source 2,1 not defined (VLC_SOURCE_2X1)"
    exit 1
fi

if [ -z "${VLC_SOURCE_3X1}" ]; then
    echo "Source 3,1 not defined (VLC_SOURCE_3X1)"
    exit 1
fi

if [ -z "${VLC_SOURCE_1X2}" ]; then
    echo "Source 1,2 not defined (VLC_SOURCE_1X2)"
    exit 1
fi

if [ -z "${VLC_SOURCE_2X2}" ]; then
    echo "Source 2,2 not defined (VLC_SOURCE_2X2)"
    exit 1
fi

if [ -z "${VLC_SOURCE_3X2}" ]; then
    echo "Source 3,2 not defined (VLC_SOURCE_3X2)"
    exit 1
fi

if [ -z "${VLC_SOURCE_1X3}" ]; then
    echo "Source 1,3 not defined (VLC_SOURCE_1X3)"
    exit 1
fi

if [ -z "${VLC_SOURCE_2X3}" ]; then
    echo "Source 2,3 not defined (VLC_SOURCE_2X3)"
    exit 1
fi

if [ -z "${VLC_SOURCE_3X3}" ]; then
    echo "Source 3,3 not defined (VLC_SOURCE_3X3)"
    exit 1
fi

if [ -z "${VLC_THREADS}" ]; then
    VLC_THREADS=$(nproc --all)
fi

if [ -z "${VLC_MOSAIC_WIDTH}" ]; then
    VLC_MOSAIC_WIDTH=1280
fi

if [ -z "${VLC_MOSAIC_HEIGHT}" ]; then
    VLC_MOSAIC_HEIGHT=720
fi

if [ -z "${VLC_MULTICAST_IP}" ]; then
    VLC_MULTICAST_IP=234.0.0.255
fi

if [ -z "${VLC_MULTICAST_PORT}" ]; then
    VLC_MULTICAST_PORT=1234
fi

if [ -z "${VLC_MAXRATE}" ]; then
    VLC_MAXRATE=1200
fi

if [ -z "${VLC_BUFSIZE}" ]; then
    VLC_BUFSIZE=1200
fi

if [ -z "${VLC_SAP_GROUP}" ]; then
    VLC_SAP_GROUP="Mosaic Group"
fi

if [ -z "${VLC_SAP_NAME}" ]; then
    VLC_SAP_NAME="3x3 Demo"
fi

if [ -z "${VLC_SAP_DESCRIPTION}" ]; then
    VLC_SAP_DESCRIPTION="A demonstration stream."
fi

if [ -z "${VLC_ADAPTIVE_WIDTH}" ]; then
    VLC_ADAPTIVE_WIDTH=1280
fi

if [ -z "${VLC_ADAPTIVE_HEIGHT}" ]; then
    VLC_ADAPTIVE_HEIGHT=720
fi

if [ -z "${VLC_ADAPTIVE_BITRATE}" ]; then
    VLC_ADAPTIVE_BITRATE=100000
fi

if [ -z "${VLC_ADAPTIVE_LOGIC}" ]; then
    VLC_ADAPTIVE_LOGIC=highest
fi

if [ -z "${VLC_X264}" ]; then
    VLC_X264="preset=ultrafast,tune=zerolatency,keyint=30,bframes=0,ref=1,level=30,profile=baseline,hrd=cbr,crf=20,ratetol=1.0,vbv-maxrate=${VLC_MAXRATE},vbv-bufsize=${VLC_BUFSIZE},lookahead=0"
fi

if [ -z "${VLC_FPS}" ]; then
    VLC_FPS=15
fi

if [ -z "${PORT}" ]; then
    PORT=4212
fi

if [ -z "${PASSWORD}" ]; then
    PASSWORD=vlcmulticast
fi

if [ -z "${VLC_RC_PORT}" ]; then
    VLC_RC_PORT=10101
fi

if [ -z "${VLC_TTL}" ]; then
    VLC_TTL=15
fi

if [ -z "${VLC_VERBOSE}" ]; then
    VLC_VERBOSE=0
fi

VLC_AVCODEC_OPTIONS=( "--avcodec-dr" "--avcodec-corrupted" "--avcodec-hurry-up" "--avcodec-skip-frame=1" "--avcodec-skip-idct=1" "--avcodec-fast" "--avcodec-threads" "${VLC_THREADS}" "--sout-avcodec-strict" "-2" )
# VLC_DESTINATION_STANDARD="standard{access=udp{caching=1000,ttl=15},mux=ts{use-key-frames},dst=${VLC_MULTICAST_IP}:${VLC_MULTICAST_PORT},sap,group=${VLC_SAP_GROUP},name=${VLC_SAP_NAME}}"
VLC_DESTINATION_RTP="rtp{dst=${VLC_MULTICAST_IP},port=${VLC_MULTICAST_PORT},sdp=sap://,ttl=${VLC_TTL},mux=ts{use-key-frames},proto=udp,name=${VLC_SAP_NAME@Q},description=${VLC_SAP_DESCRIPTION@Q},group=${VLC_SAP_GROUP@Q}}"
VLC_DESTINATION="dst=${VLC_DESTINATION_RTP}"

# VLC_TRANSCODE="transcode{vcodec=h264,venc=x264{${VLC_X264}},vb=${VLC_MAXRATE},fps=${VLC_FPS},threads=${VLC_THREADS}}"

mkdir -p "${HOME}"/vlc

${CONVERT} -size "${VLC_MOSAIC_WIDTH}"x"${VLC_MOSAIC_HEIGHT}" "xc:#000000" "${HOME}"/vlc/mosaic_background.png
SOURCE_WIDTH="$((VLC_MOSAIC_WIDTH / 3))"
SOURCE_HEIGHT="$((VLC_MOSAIC_HEIGHT / 3))"

cat <<EOF >"${HOME}"/vlc/mosaic.vlm
del all

new 1x1 broadcast enabled
setup 1x1 input ${VLC_SOURCE_1X1} loop
setup 1x1 output #duplicate{dst=mosaic-bridge{id=1,width=${SOURCE_WIDTH},height=${SOURCE_HEIGHT}},select=video,dst=bridge-out{id=1},select=audio}

new 2x1 broadcast enabled
setup 2x1 input ${VLC_SOURCE_2X1} loop
setup 2x1 output #duplicate{dst=mosaic-bridge{id=2,width=${SOURCE_WIDTH},height=${SOURCE_HEIGHT}},select=video,dst=bridge-out{id=2},select=audio}

new 3x1 broadcast enabled
setup 3x1 input ${VLC_SOURCE_3X1} loop
setup 3x1 output #duplicate{dst=mosaic-bridge{id=3,width=${SOURCE_WIDTH},height=${SOURCE_HEIGHT}},select=video,dst=bridge-out{id=3},select=audio}

new 1x2 broadcast enabled
setup 1x2 input ${VLC_SOURCE_1X2} loop
setup 1x2 output #duplicate{dst=mosaic-bridge{id=4,width=${SOURCE_WIDTH},height=${SOURCE_HEIGHT}},select=video,dst=bridge-out{id=4},select=audio}

new 2x2 broadcast enabled
setup 2x2 input ${VLC_SOURCE_2X2} loop
setup 2x2 output #duplicate{dst=mosaic-bridge{id=5,width=${SOURCE_WIDTH},height=${SOURCE_HEIGHT}},select=video,dst=bridge-out{id=5},select=audio}

new 3x2 broadcast enabled
setup 3x2 input ${VLC_SOURCE_3X2} loop
setup 3x2 output #duplicate{dst=mosaic-bridge{id=6,width=${SOURCE_WIDTH},height=${SOURCE_HEIGHT}},select=video,dst=bridge-out{id=6},select=audio}

new 1x3 broadcast enabled
setup 1x3 input ${VLC_SOURCE_1X3} loop
setup 1x3 output #duplicate{dst=mosaic-bridge{id=7,width=${SOURCE_WIDTH},height=${SOURCE_HEIGHT}},select=video,dst=bridge-out{id=7},select=audio}

new 2x3 broadcast enabled
setup 2x3 input ${VLC_SOURCE_2X3} loop
setup 2x3 output #duplicate{dst=mosaic-bridge{id=8,width=${SOURCE_WIDTH},height=${SOURCE_HEIGHT}},select=video,dst=bridge-out{id=8},select=audio}

new 3x3 broadcast enabled
setup 3x3 input ${VLC_SOURCE_3X3} loop
setup 3x3 output #duplicate{dst=mosaic-bridge{id=9,width=${SOURCE_WIDTH},height=${SOURCE_HEIGHT}},select=video,dst=bridge-out{id=9},select=audio}

## MOSAIC ##
new mosaic broadcast enabled 
setup mosaic option image-duration=-1
setup mosaic input ${HOME}/vlc/mosaic_background.png
setup mosaic output #transcode{sfilter=mosaic{width=${VLC_MOSAIC_WIDTH},height=${VLC_MOSAIC_HEIGHT},cols=3,rows=3,position=1,order="1,2,3,4,5,6,7,8,9",keep-aspect-ratio=enabled,keep-picture=1,align=5},fps=${VLC_FPS},vcodec=h264,threads=${VLC_THREADS}}:duplicate{${VLC_DESTINATION}}

control 1x1 play
control 2x1 play
control 3x1 play
control 1x2 play
control 2x2 play
control 3x2 play
control 1x3 play
control 2x3 play
control 3x3 play
control mosaic play

EOF

cat <<EOF
Streaming Mosaic: ${VLC_SAP_GROUP}/${VLC_SAP_NAME}
Mosaic Dimensions: ${VLC_MOSAIC_WIDTH}x${VLC_MOSAIC_HEIGHT}
Video Dimensions: ${SOURCE_WIDTH}x${SOURCE_HEIGHT}
Multicast: ${VLC_MULTICAST_IP}:${VLC_MULTICAST_PORT}
Sources:
 1,1 ${VLC_SOURCE_1X1}
 2,1 ${VLC_SOURCE_2X1}
 3,1 ${VLC_SOURCE_3X1}
 1,2 ${VLC_SOURCE_1X2}
 2,2 ${VLC_SOURCE_2X2}
 3,2 ${VLC_SOURCE_3X2}
 1,3 ${VLC_SOURCE_1X3}
 2,3 ${VLC_SOURCE_2X3}
 3,3 ${VLC_SOURCE_3X3}
EOF

# VLC_COMMAND="${VLC} -I telnet --telnet-password=${PASSWORD} --telnet-port=${PORT} --no-media-library --verbose=${VLC_VERBOSE} --vlm-conf=${HOME}/vlc/mosaic.vlm --no-disable-screensaver ${VLC_AVCODEC_OPTIONS} --no-repeat --no-loop --network-caching=${VLC_CACHE} --drop-late-frames --skip-frames --no-daemon --adaptive-logic=${VLC_ADAPTIVE_LOGIC} --adaptive-maxwidth=${VLC_ADAPTIVE_WIDTH} --adaptive-maxheight=${VLC_ADAPTIVE_HEIGHT} --adaptive-bw=${VLC_ADAPTIVE_BITRATE}"
VLC_COMMAND=( "-I" "telnet" "--telnet-password" "${PASSWORD}" "--telnet-port" "${PORT}" "--no-media-library" "--verbose" "${VLC_VERBOSE}" "--vlm-conf" "${HOME}/vlc/mosaic.vlm" "--no-disable-screensaver" "${VLC_AVCODEC_OPTIONS[@]}" "--no-repeat" "--no-loop" "--network-caching" "${VLC_CACHE}" "--drop-late-frames" "--skip-frames" "--no-daemon" "--adaptive-logic" "${VLC_ADAPTIVE_LOGIC}" "--adaptive-maxwidth" "${VLC_ADAPTIVE_WIDTH}" "--adaptive-maxheight" "${VLC_ADAPTIVE_HEIGHT}" "--adaptive-bw" "${VLC_ADAPTIVE_BITRATE}" )
echo "📺 Starting VLC Stream ${VLC_SAP_GROUP}/${VLC_SAP_NAME}"
printf "🖥 Running: %s\n" "vlc " "${VLC_COMMAND[@]}"
# shellcheck disable=SC2086
nice -n -20 ${VLC} "${VLC_COMMAND[@]}" &
vlcpid=$!
echo "🆔 VLC Running as PID ${vlcpid}"
cat "${HOME}/vlc/mosaic.vlm"
wait "$vlcpid"
rm -f "${HOME}"/vlc/mosaic.vlm
echo "👋 VLC Stream ${VLC_SAP_GROUP}/${VLC_SAP_NAME} Finished"
